import { AnalysisHubResponse, DatasetRun, PipelineLog } from '../types';

export const getMockAnalysisData = (period: string = 'weekly'): AnalysisHubResponse => {
  const isDaily = period === 'daily';
  const isMonthly = period === 'monthly';
  const multiplier = isDaily ? 0.2 : isMonthly ? 4.2 : 1.0;
  const baseVolume = Math.round(14850 * multiplier);

  return {
    status: 'success',
    kpis: {
      total_conversations: baseVolume,
      resolution_rate: 84.5,
      escalation_rate: 14.2,
      reopen_rate: 4.2,
      avg_response_time_minutes: 49.5,
      negative_sentiment_percentage: 21.5,
      positive_sentiment_percentage: 21.5,
      neutral_sentiment_percentage: 57.0,
      first_contact_resolution_rate: 74.2,
      sla_breach_rate: 3.1,
      customer_satisfaction_score: 4.3,
      total_agents_active: 48,
    },
    kpi_pillars: {
      issue_reduction_over_time: {
        reduction_rate_percentage: -18.4,
        recurring_tickets_count: 11,
        baseline_cases: 174,
        trend: 'improving',
      },
      sentiment_impact: {
        negative_share_percentage: 21.5,
        escalation_multiplier: 3.8,
        high_risk_volume: 3178,
        delta_escalation_pct: 42.5,
      },
      fast_mean_response_time: {
        value_minutes: 49.5,
        avg_resolution_proxy_minutes: 143.8,
        sla_compliance_rate: 96.9,
        speedup_pct: 28.4,
      },
      ai_proposed_solution_impact: {
        resolution_speedup_percentage: 36.2,
        cost_savings_estimated: 42800,
        automated_resolutions_pct: 54.7,
      },
    },
    sentiment_distribution: {
      positive: { count: Math.round(baseVolume * 0.215), percentage: 21.5 },
      neutral: { count: Math.round(baseVolume * 0.570), percentage: 57.0 },
      negative: { count: Math.round(baseVolume * 0.215), percentage: 21.5 },
    },
    topic_summaries: [
      {
        topic_id: 'top-1',
        topic: 'App Startup Freeze & Splash Screen Crash',
        cluster_name: 'App Performance & Stability',
        keywords: ['freeze_on_startup', 'v2_4_1_patch', 'black_screen', 'crash_loop'],
        volume: 3820,
        percentage: 25.7,
        negative_percentage: 64.2,
        escalation_rate: 18.5,
        avg_response_time: 42.4,
        priority: 'Critical',
        sentiment: 'negative',
        sample_utterances: [
          'App freezes on startup after 2.4.1 patch.',
          'Unable to open order tracking, screen goes black and forces closed.',
          'Splash screen hangs indefinitely on Android 14 devices.',
          'App crashes immediately upon launching checkout page.',
        ],
        sentiment_breakdown: { positive: 6, neutral: 30, negative: 64 },
      },
      {
        topic_id: 'top-2',
        topic: 'Battery & Power Optimization Drain',
        cluster_name: 'Battery & Power Optimization',
        keywords: ['battery_drain', 'overheating', 'background_sync', 'power_loss'],
        volume: 2940,
        percentage: 19.8,
        negative_percentage: 58.4,
        escalation_rate: 14.2,
        avg_response_time: 48.0,
        priority: 'High',
        sentiment: 'negative',
        sample_utterances: [
          'Battery drains 30% in 1 hour after update.',
          'Phone gets unusually warm while running background location tracking.',
          'Severe battery consumption during passive notification sync.',
        ],
        sentiment_breakdown: { positive: 8, neutral: 34, negative: 58 },
      },
      {
        topic_id: 'top-3',
        topic: 'Payment Gateway Timeout & Double Debits',
        cluster_name: 'Billing & Payments',
        keywords: ['double_charge', 'checkout_timeout', 'card_declined', 'upi_pending'],
        volume: 2410,
        percentage: 16.2,
        negative_percentage: 52.6,
        escalation_rate: 16.8,
        avg_response_time: 38.5,
        priority: 'Critical',
        sentiment: 'negative',
        sample_utterances: [
          'My card was debited twice but the order status is still showing failed.',
          'Payment gateway timed out during credit card 3D Secure OTP verification.',
          'UPI transaction deducted from bank account without generating confirmation invoice.',
        ],
        sentiment_breakdown: { positive: 10, neutral: 37, negative: 53 },
      },
      {
        topic_id: 'top-4',
        topic: 'Network Connectivity & Webhook Latency',
        cluster_name: 'Network & Infrastructure',
        keywords: ['webhook_504', 'api_timeout', 'network_error', 'slow_sync'],
        volume: 2180,
        percentage: 14.7,
        negative_percentage: 38.2,
        escalation_rate: 9.4,
        avg_response_time: 52.0,
        priority: 'Medium',
        sentiment: 'neutral',
        sample_utterances: [
          'Received 504 Gateway Timeout while synchronizing enterprise webhook payload.',
          'API latency increased to over 4.5 seconds on regional Europe cluster.',
        ],
        sentiment_breakdown: { positive: 18, neutral: 44, negative: 38 },
      },
      {
        topic_id: 'top-5',
        topic: 'Subscription Auto-Renewal & GST Invoice Requests',
        cluster_name: 'Account & Billing',
        keywords: ['auto_renew', 'gst_invoice', 'cancel_subscription', 'refund_policy'],
        volume: 1860,
        percentage: 12.5,
        negative_percentage: 31.0,
        escalation_rate: 6.2,
        avg_response_time: 44.0,
        priority: 'Medium',
        sentiment: 'neutral',
        sample_utterances: [
          'Where can I download the GST tax invoice for annual billing?',
          'Need to confirm subscription cancellation and stop upcoming auto-renewal.',
        ],
        sentiment_breakdown: { positive: 24, neutral: 45, negative: 31 },
      },
      {
        topic_id: 'top-6',
        topic: 'Product Feature Praise & Positive Feedback',
        cluster_name: 'Customer Delight',
        keywords: ['fast_support', 'love_feature', 'smooth_ui', 'helpful_agent'],
        volume: 1640,
        percentage: 11.1,
        negative_percentage: 2.1,
        escalation_rate: 0.4,
        avg_response_time: 22.0,
        priority: 'Low',
        sentiment: 'positive',
        sample_utterances: [
          'Super fast response from the care team, query resolved in 5 minutes!',
          'The new analytics view and report generator are smooth and easy to navigate.',
        ],
        sentiment_breakdown: { positive: 88, neutral: 10, negative: 2 },
      },
    ],
    customer_pain_points: [
      {
        topic_id: 'top-1',
        topic: 'App Startup Freeze & Splash Screen Crash',
        cluster_name: 'App Performance & Stability',
        keywords: ['freeze_on_startup', 'v2_4_1_patch', 'black_screen'],
        volume: 3820,
        negative_percentage: 64.2,
        escalation_rate: 18.5,
        avg_response_time: 42.4,
        priority: 'Critical',
        sample_utterances: [
          'App freezes on startup after 2.4.1 patch.',
          'Unable to open order tracking, screen goes black and forces closed.',
        ],
      },
      {
        topic_id: 'top-2',
        topic: 'Battery & Power Optimization Drain',
        cluster_name: 'Battery & Power Optimization',
        keywords: ['battery_drain', 'overheating', 'background_sync'],
        volume: 2940,
        negative_percentage: 58.4,
        escalation_rate: 14.2,
        avg_response_time: 48.0,
        priority: 'High',
        sample_utterances: [
          'Battery drains 30% in 1 hour after update.',
          'Phone gets unusually warm while running background location tracking.',
        ],
      },
      {
        topic_id: 'top-3',
        topic: 'Payment Gateway Timeout & Double Debits',
        cluster_name: 'Billing & Payments',
        keywords: ['double_charge', 'checkout_timeout', 'upi_pending'],
        volume: 2410,
        negative_percentage: 52.6,
        escalation_rate: 16.8,
        avg_response_time: 38.5,
        priority: 'Critical',
        sample_utterances: [
          'My card was debited twice but the order status is still showing failed.',
          'Payment gateway timed out during credit card 3D Secure OTP verification.',
        ],
      },
    ],
    emerging_issues: [
      {
        topic: 'Android 14 Startup Splash Screen Crash (+35% Spike - Immediate L2 Action)',
        keywords: ['android_14', 'v2_4_1_patch', 'splash_crash'],
        growth_rate_percentage: 35.0,
        current_volume: 2410,
        previous_volume: 1785,
        negative_complaints: 1547,
        escalation_risk: 'Critical',
        action_urgency: '+35% Spike — Immediate L2 Action Required',
      },
      {
        topic: 'Battery Drain Surge in Background Location Sync',
        keywords: ['battery_drain', 'power_loss', 'sync_loop'],
        growth_rate_percentage: 28.4,
        current_volume: 1820,
        previous_volume: 1417,
        negative_complaints: 1062,
        escalation_risk: 'High',
        action_urgency: 'Scale Worker Cluster & Patch Telemetry Loop',
      },
      {
        topic: 'Regional Europe Webhook 504 Timeout',
        keywords: ['webhook_504', 'api_timeout', 'eu_central'],
        growth_rate_percentage: 22.1,
        current_volume: 640,
        previous_volume: 524,
        negative_complaints: 390,
        escalation_risk: 'High',
        action_urgency: 'Server Replica Scaling',
      },
    ],
    recurring_issues: [
      {
        topic: 'Payment Gateway Double Debits on Timeout',
        total_recurrences: 142,
        reopen_probability: 18.2,
        avg_resolution_bottleneck_min: 44.5,
        status: 'Fix Pending',
      },
      {
        topic: 'SMS 2FA Delivery Delay on Regional Telco Gateways',
        total_recurrences: 98,
        reopen_probability: 12.4,
        avg_resolution_bottleneck_min: 28.1,
        status: 'Monitoring',
      },
      {
        topic: 'Invoice PDF Download Generating Corrupt Headers',
        total_recurrences: 64,
        reopen_probability: 9.8,
        avg_resolution_bottleneck_min: 19.4,
        status: 'Investigating',
      },
    ],
    new_issues: [
      {
        topic: 'Apple Pay Checkout Authorization Failure in EU Region',
        initial_volume: 380,
        severity_level: 'High',
        first_detected: '2026-08-14 09:20 UTC',
        source_channel: 'Twitter Support & In-App Chat',
      },
      {
        topic: 'Dark Mode Contrast Glitch in Order Summary View',
        initial_volume: 124,
        severity_level: 'Low',
        first_detected: '2026-08-15 04:15 UTC',
        source_channel: 'Community Forum',
      },
    ],
    priorities: [
      {
        rank: 1,
        topic: 'App Startup Freeze & Splash Screen Crash (Queue 1: P1 High Priority)',
        case_volume: 3820,
        negative_complaints: 2452,
        sla_response_target: 'SLA < 30 mins (Queue 1: High Priority)',
        urgency_score: 96,
        owner_team: 'Mobile Client Engineering',
      },
      {
        rank: 2,
        topic: 'Payment Gateway Timeout & Double Debits (Queue 1: P1 High Priority)',
        case_volume: 2410,
        negative_complaints: 1267,
        sla_response_target: 'SLA < 30 mins (Queue 1: High Priority)',
        urgency_score: 92,
        owner_team: 'Billing & Fintech Squad',
      },
      {
        rank: 3,
        topic: 'Battery Drain & Overheating (Queue 2: P2 Medium Priority)',
        case_volume: 2940,
        negative_complaints: 1716,
        sla_response_target: 'SLA < 60 mins (Queue 2: Medium Priority)',
        urgency_score: 84,
        owner_team: 'Core Platform Squad',
      },
      {
        rank: 4,
        topic: 'General Inquiries & Invoice PDF Requests (Queue 3: P3 Normal Priority)',
        case_volume: 1860,
        negative_complaints: 576,
        sla_response_target: 'SLA < 120 mins (Queue 3: Normal Priority)',
        urgency_score: 65,
        owner_team: 'Customer Care Operations',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        topic: 'App Startup Freeze on v2.4.1',
        root_cause: 'Null-pointer exception in hardware graphics shader pipeline when rendering animated vector carts on API level 34.',
        affected_users_pct: 25.7,
        suggested_remedy: 'Ship patch v2.4.2 immediately with hardware shader acceleration disabled for legacy devices.',
        estimated_impact: 'Reduces app crash complaints by 92% across 85,000 active devices.',
        status: 'In Progress',
      },
      {
        id: 'rec-2',
        topic: 'Payment Gateway Timeout Resilience',
        root_cause: 'Secondary payment provider webhook timeout under peak traffic spikes causing unconfirmed client statuses.',
        affected_users_pct: 16.2,
        suggested_remedy: 'Deploy automated idempotency check and multi-provider circuit breaker failover to Adyen/Stripe.',
        estimated_impact: 'Eliminates 78% of double-charge inquiries and recovers ~$120k/mo in abandoned checkouts.',
        status: 'Open',
      },
      {
        id: 'rec-3',
        topic: 'Background Location Battery Consumption',
        root_cause: 'High-frequency GPS polling interval set to 15 seconds instead of 180 seconds during passive order tracking.',
        affected_users_pct: 19.8,
        suggested_remedy: 'Update location throttle interval with geofence triggers to eliminate unnecessary GPS wakeups.',
        estimated_impact: 'Extends device battery life by +3.5 hours during active session tracking.',
        status: 'Mitigated',
      },
    ],
    root_cause_analysis: [
      {
        id: 'rc-1',
        topic: 'App Startup Freeze',
        root_cause: 'Hardware shader acceleration crash on Android 14 devices.',
        affected_users_pct: 25.7,
        suggested_remedy: 'Disable hardware layer acceleration for animated splash components.',
        estimated_impact: 'Resolves 92% of crash inquiries.',
        status: 'In Progress',
      },
    ],
    trends: {
      daily: [
        { date: 'Mon', total_volume: 1840, positive_volume: 395, negative_volume: 395, neutral_volume: 1050, avg_response_time: 48.2, is_spike: false, z_score: 0.4 },
        { date: 'Tue', total_volume: 2120, positive_volume: 455, negative_volume: 455, neutral_volume: 1210, avg_response_time: 49.0, is_spike: false, z_score: 0.8 },
        { date: 'Wed', total_volume: 3450, positive_volume: 741, negative_volume: 1240, neutral_volume: 1469, avg_response_time: 58.4, is_spike: true, z_score: 3.2, spike_reason: 'Android 14 App Update Crash Spike' },
        { date: 'Thu', total_volume: 2650, positive_volume: 569, negative_volume: 569, neutral_volume: 1512, avg_response_time: 49.5, is_spike: false, z_score: 1.4 },
        { date: 'Fri', total_volume: 2280, positive_volume: 490, negative_volume: 490, neutral_volume: 1300, avg_response_time: 47.5, is_spike: false, z_score: 0.9 },
        { date: 'Sat', total_volume: 1340, positive_volume: 288, negative_volume: 288, neutral_volume: 764, avg_response_time: 45.2, is_spike: false, z_score: 0.2 },
        { date: 'Sun', total_volume: 1170, positive_volume: 251, negative_volume: 251, neutral_volume: 668, avg_response_time: 44.8, is_spike: false, z_score: 0.1 },
      ],
      spikes: [
        { date: '2026-08-13', z_score: 3.2, topic: 'Android 14 App Release Crash Surge (+35% Spike)' },
      ],
    },
    llm_summary: `### 🎯 Executive Directives & Boss Summary

**1. Primary Operational Highlights:**
Overall customer support conversation volume reached **14,850 interactions** with an improving resolution efficiency of **84.5%**. First Contact Resolution (FCR) is healthy at **74.2%**, and the mean response time remains optimized at **49.5 minutes** (well within the target SLA of < 60 mins).

**2. Key Risk Areas & Emerging Anomalies:**
- **🚨 Critical Anomaly (+35% Surge):** A severe volume spike occurred following the v2.4.1 release, driving 3,820 customer complaints regarding app freezes on startup.
- **🔋 Battery Optimization:** Background location polling during delivery tracking caused a +28.4% surge in battery drain complaints.
- **💳 Payment Inquiries:** Payment gateway timeouts and duplicate charges account for 16.2% of total volume with a 52.6% negative sentiment friction.

**3. Actionable AI Recommendations for Product & Engineering:**
- **Engineering Action:** Ship mobile client patch v2.4.2 immediately with hardware shader acceleration disabled for legacy devices.
- **Fintech / Payment Squad:** Implement automatic multi-provider circuit breaking on checkout to reroute failed payment intents without duplicate card debits.
- **Support Operations:** Deploy the Voila AI Suggested Response Copilot across the Billing and Technical queues to maintain the **+36.2% resolution speedup**.`,
  };
};

export const mockDatasetRuns: DatasetRun[] = [
  {
    run_id: 'run-w32-2026',
    dataset_name: 'Social Support Conversations (Week 32)',
    filename: 'social_support_w32.csv',
    timestamp: '2026-08-15 08:30 UTC',
    created_at: '2026-08-15 08:30 UTC',
    total_rows: 14850,
    rows_count: 14850,
    user_id: 'deepak',
    status: 'ACTIVE',
  },
  {
    run_id: 'run-w31-2026',
    dataset_name: 'Social Support Conversations (Week 31)',
    filename: 'social_support_w31.csv',
    timestamp: '2026-08-08 12:15 UTC',
    created_at: '2026-08-08 12:15 UTC',
    total_rows: 14200,
    rows_count: 14200,
    user_id: 'deepak',
    status: 'ARCHIVED',
  },
];

export const mockPipelineLogs: PipelineLog[] = [
  { run_id: 'run-w32-2026', step: '1. Ingest Raw Dataset Stream', status: 'SUCCESS', timestamp: '2026-08-15 08:30:02' },
  { run_id: 'run-w32-2026', step: '2. Text Normalization & PII Masking', status: 'SUCCESS', timestamp: '2026-08-15 08:30:14' },
  { run_id: 'run-w32-2026', step: '3. Transformer Sentiment & Emotion Inference', status: 'SUCCESS', timestamp: '2026-08-15 08:30:38' },
  { run_id: 'run-w32-2026', step: '4. HDBSCAN & TF-IDF Topic Clustering', status: 'SUCCESS', timestamp: '2026-08-15 08:30:52' },
  { run_id: 'run-w32-2026', step: '5. Z-Score Anomaly & Spike Detection', status: 'SUCCESS', timestamp: '2026-08-15 08:31:05' },
  { run_id: 'run-w32-2026', step: '6. 15 Operational Metrics Aggregation', status: 'SUCCESS', timestamp: '2026-08-15 08:31:18' },
  { run_id: 'run-w32-2026', step: '7. GenAI Executive Directives Grounding', status: 'SUCCESS', timestamp: '2026-08-15 08:31:26' },
];
