import { AnalysisHubResponse, DatasetRun, PipelineLog } from '../types';

export const getMockAnalysisData = (period: string = 'weekly'): AnalysisHubResponse => {
  const isDaily = period === 'daily';
  const isMonthly = period === 'monthly';

  const multiplier = isDaily ? 0.2 : isMonthly ? 4.2 : 1.0;
  const baseVolume = Math.round(14850 * multiplier);

  return {
    status: 'success',
    kpis: {
      total_conversations: baseVolume,
      resolution_rate: 89.4,
      escalation_rate: 7.8,
      reopen_rate: 4.2,
      avg_response_time_minutes: 18.5,
      negative_sentiment_percentage: 21.4,
      positive_sentiment_percentage: 42.6,
      neutral_sentiment_percentage: 36.0,
      first_contact_resolution_rate: 74.2,
      sla_breach_rate: 3.1,
      customer_satisfaction_score: 4.3,
      total_agents_active: 48,
    },
    kpi_pillars: {
      issue_reduction_over_time: {
        reduction_rate_percentage: -18.4,
        recurring_tickets_count: 142,
        baseline_cases: 174,
        trend: 'improving',
      },
      sentiment_impact: {
        negative_share_percentage: 21.4,
        escalation_multiplier: 3.8,
        high_risk_volume: 3178,
        delta_escalation_pct: 42.5,
      },
      fast_mean_response_time: {
        value_minutes: 18.5,
        avg_resolution_proxy_minutes: 142.6,
        sla_compliance_rate: 96.9,
        speedup_pct: 28.4,
      },
      ai_proposed_solution_impact: {
        resolution_speedup_percentage: 36.2,
        cost_savings_estimated: 42800,
        automated_resolutions_pct: 54.7,
      },
    },
    sentiment_distribution: {
      positive: { count: Math.round(baseVolume * 0.426), percentage: 42.6 },
      neutral: { count: Math.round(baseVolume * 0.360), percentage: 36.0 },
      negative: { count: Math.round(baseVolume * 0.214), percentage: 21.4 },
    },
    topic_summaries: [
      {
        topic_id: 'top-1',
        topic: 'Payment Gateway Timeout & Double Debits',
        cluster_name: 'Billing & Payments',
        keywords: ['card_declined', 'double_charge', 'checkout_timeout', 'refund_delay', 'upi_failed'],
        volume: Math.round(3820 * multiplier),
        percentage: 25.7,
        negative_percentage: 64.2,
        escalation_rate: 14.8,
        avg_response_time: 14.2,
        priority: 'Critical',
        sentiment: 'negative',
        sample_utterances: [
          'My payment was deducted twice on checkout but order is still showing pending!',
          'Payment gateway timed out during credit card OTP verification.',
          'Double charge on card for transaction #88921. Need immediate refund.',
          'UPI transaction failed but money debited from bank account.',
        ],
        sentiment_breakdown: { positive: 8, neutral: 28, negative: 64 },
      },
      {
        topic_id: 'top-2',
        topic: 'Subscription Auto-Renewal & Cancellation',
        cluster_name: 'Account & Billing',
        keywords: ['auto_renew', 'cancel_subscription', 'refund_policy', 'invoice_missing'],
        volume: Math.round(2940 * multiplier),
        percentage: 19.8,
        negative_percentage: 42.1,
        escalation_rate: 8.5,
        avg_response_time: 16.8,
        priority: 'High',
        sentiment: 'negative',
        sample_utterances: [
          'I requested cancellation last week why was my card charged again today?',
          'Where can I download the GST invoice for my annual plan?',
          'Cancel membership renewal immediately and confirm.',
        ],
        sentiment_breakdown: { positive: 18, neutral: 40, negative: 42 },
      },
      {
        topic_id: 'top-3',
        topic: 'Mobile App Crash on Android 14',
        cluster_name: 'App Performance',
        keywords: ['crash_on_launch', 'android_14', 'black_screen', 'freeze_cart', 'update_bug'],
        volume: Math.round(2410 * multiplier),
        percentage: 16.2,
        negative_percentage: 58.6,
        escalation_rate: 12.4,
        avg_response_time: 21.0,
        priority: 'Critical',
        sentiment: 'negative',
        sample_utterances: [
          'App keeps crashing every time I open the order tracking tab on Pixel 8.',
          'Freezes immediately on splash screen after latest 4.2.1 build.',
          'Unable to complete checkout - app goes completely black screen.',
        ],
        sentiment_breakdown: { positive: 5, neutral: 36, negative: 59 },
      },
      {
        topic_id: 'top-4',
        topic: 'Courier Logistics & Late Delivery Inquiries',
        cluster_name: 'Logistics & Shipping',
        keywords: ['tracking_delayed', 'courier_delay', 'out_for_delivery', 'wrong_address'],
        volume: Math.round(2180 * multiplier),
        percentage: 14.7,
        negative_percentage: 38.4,
        escalation_rate: 6.2,
        avg_response_time: 12.4,
        priority: 'Medium',
        sentiment: 'neutral',
        sample_utterances: [
          'Courier tracking status has not updated in the last 48 hours.',
          'Was supposed to arrive yesterday, need urgent delivery confirmation.',
          'Delivery agent marked customer not reachable without calling.',
        ],
        sentiment_breakdown: { positive: 22, neutral: 40, negative: 38 },
      },
      {
        topic_id: 'top-5',
        topic: 'Account Login & 2FA SMS Delivery Delays',
        cluster_name: 'Authentication',
        keywords: ['sms_otp', '2fa_not_received', 'password_reset', 'locked_account'],
        volume: Math.round(1860 * multiplier),
        percentage: 12.5,
        negative_percentage: 31.2,
        escalation_rate: 4.8,
        avg_response_time: 9.5,
        priority: 'Medium',
        sentiment: 'neutral',
        sample_utterances: [
          'SMS verification code takes over 10 minutes to arrive on phone.',
          'Locked out of my account after multiple attempts due to OTP delay.',
          'Need to change registered phone number for two-factor authentication.',
        ],
        sentiment_breakdown: { positive: 25, neutral: 44, negative: 31 },
      },
      {
        topic_id: 'top-6',
        topic: 'Product Feature Praises & Positive Feedback',
        cluster_name: 'Customer Delight',
        keywords: ['fast_support', 'love_feature', 'smooth_ui', 'great_experience', 'helpful_agent'],
        volume: Math.round(1640 * multiplier),
        percentage: 11.1,
        negative_percentage: 2.1,
        escalation_rate: 0.4,
        avg_response_time: 8.2,
        priority: 'Low',
        sentiment: 'positive',
        sample_utterances: [
          'Super fast response from support team, resolved my query in 3 minutes!',
          'The new dark mode and analytics dashboard UI is incredible.',
          'Thank you for the quick replacement shipment!',
        ],
        sentiment_breakdown: { positive: 88, neutral: 10, negative: 2 },
      },
    ],
    customer_pain_points: [
      {
        topic_id: 'top-1',
        topic: 'Payment Gateway Timeout & Double Debits',
        cluster_name: 'Billing & Payments',
        keywords: ['card_declined', 'double_charge', 'checkout_timeout'],
        volume: Math.round(3820 * multiplier),
        negative_percentage: 64.2,
        escalation_rate: 14.8,
        avg_response_time: 14.2,
        priority: 'Critical',
      },
      {
        topic_id: 'top-3',
        topic: 'Mobile App Crash on Android 14',
        cluster_name: 'App Performance',
        keywords: ['crash_on_launch', 'android_14', 'black_screen'],
        volume: Math.round(2410 * multiplier),
        negative_percentage: 58.6,
        escalation_rate: 12.4,
        avg_response_time: 21.0,
        priority: 'Critical',
      },
      {
        topic_id: 'top-2',
        topic: 'Subscription Auto-Renewal & Cancellation',
        cluster_name: 'Account & Billing',
        keywords: ['auto_renew', 'cancel_subscription', 'refund_policy'],
        volume: Math.round(2940 * multiplier),
        negative_percentage: 42.1,
        escalation_rate: 8.5,
        avg_response_time: 16.8,
        priority: 'High',
      },
    ],
    emerging_issues: [
      {
        topic: 'Mobile App Crash on Android 14 (v4.2.1)',
        keywords: ['android_14', 'splash_crash', 'freeze'],
        growth_rate_percentage: 48.6,
        current_volume: Math.round(2410 * multiplier),
        previous_volume: Math.round(1620 * multiplier),
        negative_complaints: Math.round(1412 * multiplier),
        escalation_risk: 'Critical',
        action_urgency: 'Immediate Hotfix Deployment Needed',
      },
      {
        topic: 'Webhook Delivery Timeout on Enterprise Tier',
        keywords: ['webhook_504', 'api_timeout', 'payload_retry'],
        growth_rate_percentage: 31.4,
        current_volume: Math.round(620 * multiplier),
        previous_volume: Math.round(470 * multiplier),
        negative_complaints: Math.round(380 * multiplier),
        escalation_risk: 'High',
        action_urgency: 'Scale Worker Cluster',
      },
      {
        topic: 'OAuth2 Token Expiration Re-Authentication Loop',
        keywords: ['oauth_refresh', 'session_expired', 'infinite_redirect'],
        growth_rate_percentage: 24.2,
        current_volume: Math.round(410 * multiplier),
        previous_volume: Math.round(330 * multiplier),
        negative_complaints: Math.round(210 * multiplier),
        escalation_risk: 'Medium',
        action_urgency: 'Token Life Extension Review',
      },
    ],
    recurring_issues: [
      {
        topic: 'Payment Gateway Timeout & Double Debits',
        total_recurrences: 142,
        reopen_probability: 18.2,
        avg_resolution_bottleneck_min: 44.5,
        status: 'Fix Pending',
      },
      {
        topic: 'Password Reset SMS Delayed / Telco Gateway Failure',
        total_recurrences: 98,
        reopen_probability: 12.4,
        avg_resolution_bottleneck_min: 28.1,
        status: 'Monitoring',
      },
      {
        topic: 'Invoice PDF Download Generating Corrupt Headers',
        total_recurrences: 64,
        reopen_probability: 9.8,
        avg_resolution_bottleneck_min: 19.4,
        status: 'Investigating',
      },
    ],
    new_issues: [
      {
        topic: 'Apple Pay Checkout Authorization Failure in EU Region',
        initial_volume: 380,
        severity_level: 'High',
        first_detected: '2026-08-14 09:20 UTC',
        source_channel: 'Twitter Support & In-App Chat',
      },
      {
        topic: 'Dark Mode Contrast Glitch in Order Summary View',
        initial_volume: 124,
        severity_level: 'Low',
        first_detected: '2026-08-15 04:15 UTC',
        source_channel: 'Community Forum',
      },
    ],
    priorities: [
      {
        rank: 1,
        topic: 'Payment Gateway Timeout & Double Debits',
        case_volume: Math.round(3820 * multiplier),
        negative_complaints: Math.round(2450 * multiplier),
        sla_response_target: '< 15 mins (Priority 1)',
        urgency_score: 96,
        owner_team: 'Core Billing Squad',
      },
      {
        rank: 2,
        topic: 'Android 14 App Crash on Launch',
        case_volume: Math.round(2410 * multiplier),
        negative_complaints: Math.round(1412 * multiplier),
        sla_response_target: '< 30 mins (Priority 1)',
        urgency_score: 92,
        owner_team: 'Mobile Client Engineering',
      },
      {
        rank: 3,
        topic: 'Subscription Auto-Renewal Dispute Queue',
        case_volume: Math.round(2940 * multiplier),
        negative_complaints: Math.round(1238 * multiplier),
        sla_response_target: '< 1 hour (Priority 2)',
        urgency_score: 84,
        owner_team: 'Customer Care Lead',
      },
      {
        rank: 4,
        topic: 'Delayed Tracking Updates on Regional Couriers',
        case_volume: Math.round(2180 * multiplier),
        negative_complaints: Math.round(837 * multiplier),
        sla_response_target: '< 2 hours (Priority 3)',
        urgency_score: 71,
        owner_team: 'Logistics Operations',
      },
    ],
    recommendations: [
      {
        id: 'rec-1',
        topic: 'Payment Gateway Resilience',
        root_cause: 'Secondary payment provider webhook timeout under peak traffic spikes causing unconfirmed client statuses.',
        affected_users_pct: 25.7,
        suggested_remedy: 'Deploy automated idempotency check and multi-provider circuit breaker failover to Adyen/Stripe.',
        estimated_impact: 'Eliminates 78% of double-charge inquiries and recovers ~$120k/mo in abandoned checkouts.',
        status: 'In Progress',
      },
      {
        id: 'rec-2',
        topic: 'Android 14 Jetpack Compose Crash',
        root_cause: 'Null-pointer exception in hardware graphics acceleration pipeline when rendering animated SVG carts on API level 34.',
        affected_users_pct: 16.2,
        suggested_remedy: 'Ship patch v4.2.2 with hardware layer fallback enabled for legacy shader support.',
        estimated_impact: 'Reduces app crash rate from 4.8% to <0.2% across 85,000 active devices.',
        status: 'Open',
      },
      {
        id: 'rec-3',
        topic: 'Self-Service Subscription Cancellation',
        root_cause: 'Complex multi-step cancellation flow in account settings forces users to open support tickets.',
        affected_users_pct: 19.8,
        suggested_remedy: 'Implement 1-click self-service pause & cancel wizard with instant prorated credit calculation.',
        estimated_impact: 'Cuts support ticket volume by 18.4% and increases customer retention satisfaction by +22 NPS points.',
        status: 'Mitigated',
      },
    ],
    root_cause_analysis: [
      {
        id: 'rc-1',
        topic: 'Payment Gateway Timeout',
        root_cause: 'Database connection pool saturation during peak discount flash sales.',
        affected_users_pct: 25.7,
        suggested_remedy: 'Scale RDS read replicas and implement Redis request queue.',
        estimated_impact: 'Response latency reduced to <120ms.',
        status: 'In Progress',
      },
    ],
    trends: {
      daily: [
        { date: 'Mon', total_volume: 1840, positive_volume: 780, negative_volume: 390, neutral_volume: 670, avg_response_time: 19.2, is_spike: false, z_score: 0.4 },
        { date: 'Tue', total_volume: 2120, positive_volume: 910, negative_volume: 450, neutral_volume: 760, avg_response_time: 18.4, is_spike: false, z_score: 0.8 },
        { date: 'Wed', total_volume: 3450, positive_volume: 1100, negative_volume: 1420, neutral_volume: 930, avg_response_time: 26.8, is_spike: true, z_score: 3.2, spike_reason: 'Android 14 App Update Crash Spike' },
        { date: 'Thu', total_volume: 2650, positive_volume: 1050, negative_volume: 680, neutral_volume: 920, avg_response_time: 20.1, is_spike: false, z_score: 1.4 },
        { date: 'Fri', total_volume: 2280, positive_volume: 990, negative_volume: 460, neutral_volume: 830, avg_response_time: 17.5, is_spike: false, z_score: 0.9 },
        { date: 'Sat', total_volume: 1340, positive_volume: 620, negative_volume: 240, neutral_volume: 480, avg_response_time: 15.2, is_spike: false, z_score: 0.2 },
        { date: 'Sun', total_volume: 1170, positive_volume: 580, negative_volume: 180, neutral_volume: 410, avg_response_time: 14.8, is_spike: false, z_score: 0.1 },
      ],
      weekly: [
        { date: 'Week 28', total_volume: 12400, positive_volume: 5100, negative_volume: 2900, neutral_volume: 4400, avg_response_time: 22.4, is_spike: false, z_score: 0.5 },
        { date: 'Week 29', total_volume: 13100, positive_volume: 5400, negative_volume: 2800, neutral_volume: 4900, avg_response_time: 20.8, is_spike: false, z_score: 0.7 },
        { date: 'Week 30', total_volume: 16800, positive_volume: 6200, negative_volume: 4800, neutral_volume: 5800, avg_response_time: 28.5, is_spike: true, z_score: 2.8, spike_reason: 'Flash Sale Payment Outage' },
        { date: 'Week 31', total_volume: 14200, positive_volume: 5900, negative_volume: 3200, neutral_volume: 5100, avg_response_time: 19.5, is_spike: false, z_score: 1.1 },
        { date: 'Week 32 (Current)', total_volume: 14850, positive_volume: 6326, negative_volume: 3178, neutral_volume: 5346, avg_response_time: 18.5, is_spike: false, z_score: 1.2 },
      ],
      spikes: [
        { date: '2026-08-13', z_score: 3.2, topic: 'Android 14 App Release Crash Surge' },
        { date: '2026-08-01', z_score: 2.8, topic: 'Payment Gateway Provider Timeout' },
      ],
    },
    llm_summary: `### 🎯 Voila Voice-of-Customer Executive Directives & Strategic Summary

**1. Primary Operational Highlights:**
Overall customer support conversation volume reached **14,850 interactions** with an improving resolution efficiency of **89.4%** (+3.2% week-over-week). First Contact Resolution (FCR) is healthy at **74.2%**, and the mean response time remains optimized at **18.5 minutes** (well within SLA targets).

**2. Key Risk Areas & Emerging Anomalies:**
- **🚨 Critical Anomaly:** A significant volume spike (+48.6%) occurred following the v4.2.1 mobile app release on Android 14, driving 2,410 customer complaints centered on crash-on-launch.
- **💳 Payment Inquiries:** Payment gateway timeouts and duplicate charges represent 25.7% of all incoming negative customer sentiment (64.2% negative polarity in this cluster).

**3. Actionable AI Recommendations for Product & Engineering:**
- **Engineering Action:** Ship mobile client patch v4.2.2 immediately with hardware acceleration fallback.
- **Fintech / Payment Squad:** Implement automatic multi-provider circuit breaking on checkout to reroute failed payment intents without duplicate card debits.
- **Support Operations:** Deploy the Voila AI Suggested Response Copilot across the Billing and Subscription queues to sustain the **+36.2% resolution speedup**.`,
  };
};

export const mockDatasetRuns: DatasetRun[] = [
  {
    run_id: 'run-w32-2026',
    dataset_name: 'Social Support Conversations (Week 32)',
    filename: 'social_support_w32.csv',
    timestamp: '2026-08-15 08:30 UTC',
    created_at: '2026-08-15 08:30 UTC',
    total_rows: 14850,
    rows_count: 14850,
    user_id: 'deepak',
    status: 'ACTIVE',
  },
  {
    run_id: 'run-w31-2026',
    dataset_name: 'Social Support Conversations (Week 31)',
    filename: 'social_support_w31.csv',
    timestamp: '2026-08-08 12:15 UTC',
    created_at: '2026-08-08 12:15 UTC',
    total_rows: 14200,
    rows_count: 14200,
    user_id: 'deepak',
    status: 'ARCHIVED',
  },
  {
    run_id: 'run-w30-2026',
    dataset_name: 'Social Support Conversations (Week 30)',
    filename: 'social_support_w30.csv',
    timestamp: '2026-08-01 10:00 UTC',
    created_at: '2026-08-01 10:00 UTC',
    total_rows: 16800,
    rows_count: 16800,
    user_id: 'deepak',
    status: 'ARCHIVED',
  },
];

export const mockPipelineLogs: PipelineLog[] = [
  { run_id: 'run-w32-2026', step: '1. Ingest Raw Dataset Stream', status: 'SUCCESS', timestamp: '2026-08-15 08:30:02' },
  { run_id: 'run-w32-2026', step: '2. Text Normalization & PII Masking', status: 'SUCCESS', timestamp: '2026-08-15 08:30:14' },
  { run_id: 'run-w32-2026', step: '3. Transformer Sentiment & Emotion Inference', status: 'SUCCESS', timestamp: '2026-08-15 08:30:38' },
  { run_id: 'run-w32-2026', step: '4. HDBSCAN & TF-IDF Topic Clustering', status: 'SUCCESS', timestamp: '2026-08-15 08:30:52' },
  { run_id: 'run-w32-2026', step: '5. Z-Score Anomaly & Spike Detection', status: 'SUCCESS', timestamp: '2026-08-15 08:31:05' },
  { run_id: 'run-w32-2026', step: '6. 15 Operational Metrics Aggregation', status: 'SUCCESS', timestamp: '2026-08-15 08:31:18' },
  { run_id: 'run-w32-2026', step: '7. GenAI Executive Directives Grounding', status: 'SUCCESS', timestamp: '2026-08-15 08:31:26' },
];
